name: Gamemode4Engine
version: 1.0.0
description: This plugin handles the Gamemode 4 server backend.
author: SpiderRobotMan
website: http://www.spiderrobotman.com

main: com.spiderrobotman.Gamemode4Engine.main.Gamemode4Engine

commands:
 ban:
   description: Permanently ban a player.
   permission: gm4.ban
   usage: /ban <player> [<reason>]
 kick:
   description: Kick a player.
   permission: gm4.kick
   usage: /kick <player> [<reason>]
 tempban:
   description: Temporarily ban a player.
   permission: gm4.tempban
   usage: /tempban <player> <time> [<reason>]
 unban:
   description: Unban a player.
   permission: gm4.unban
   usage: /unban <player>
 tp:
   description: Teleport.
   aliases: [tpunsafe, teleport]
   permission: gm4.teleport
   usage: /tp <player> [<player>]
 nick:
   description: Give players a nickname.
   aliases: [nickname]
   permission: gm4.nickname
   usage: /nick <nick> [<player>]
 openinv:
   description: Open a players inventory.
   aliases: [invsee, openinventory, inventorysee]
   permission: gm4.openinv
   usage: /openinv <player>
 openend:
   description: Open a players enderchest.
   aliases: [endsee, enderchest, openenderchest, enderchestsee]
   permission: gm4.openinv
   usage: /openend <player>

permissions:
 gm4.ban:
   description: Allows you to ban players.
   default: op
 gm4.kick:
   description: Allows you to kick players.
   default: op
 gm4.kick.bypass:
   description: Allows you to bypass kick commands.
   default: op
   children:
     gm4.kick: true
 gm4.ban.bypass:
   description: Allows you to bypass ban commands.
   default: op
   children:
     gm4.ban: true
 gm4.tempban:
   description: Allows you to tempban players.
   default: op
 gm4.tempban.bypass:
   description: Allows you to bypass tempban commands.
   default: op
   children:
     gm4.tempban: true
 gm4.unban:
   description: Allows you to unban players.
   default: op
 gm4.teleport:
   description: Allows you to teleport.
   default: op
 gm4.teleport.others:
   description: Allows you to teleport others.
   default: op
   children:
     gm4.teleport: true
 gm4.nickname:
   description: Allows you to nickname yourself.
   default: op
 gm4.nickname.others:
   description: Allows you to nickname others.
   default: op
   children:
     gm4.nickname: true
 gm4.openinv:
   description: Open a players inventory.
   default: op
 gm4.openinv.bypass:
   description: Disallow allow openinv on this player.
   default: op
 gm4.openinv.override:
   description: Bypass openinv bypass.
   default: op
 gm4.openinv.edit:
   description: Allow editing of inventory.
   default: op